-- +goose Up
TRUNCATE TABLE jobs CASCADE;

ALTER TABLE jobs
DROP COLUMN IF EXISTS image_path;

ALTER TABLE jobs
DROP COLUMN IF EXISTS params;

ALTER TABLE jobs
DROP COLUMN IF EXISTS type;

DROP TYPE IF EXISTS job_type;

ALTER TABLE jobs
ADD COLUMN job_type TEXT NOT NULL;

ALTER TABLE jobs
ADD COLUMN payload JSONB NOT NULL;

-- +goose Down
ALTER TABLE jobs
DROP COLUMN IF EXISTS job_type;

ALTER TABLE jobs
DROP COLUMN IF EXISTS payload;
