// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs_query.sql

package db

import (
	"context"
	"encoding/json"
)

const createJob = `-- name: CreateJob :one

INSERT INTO jobs(type, state,image_path,params)
VALUES ($1,$2,$3,$4)
RETURNING id
`

type CreateJobParams struct {
	Type      JobType
	State     JobState
	ImagePath string
	Params    json.RawMessage
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Type,
		arg.State,
		arg.ImagePath,
		arg.Params,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
