// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs_query.sql

package db

import (
	"context"
	"encoding/json"
)

const createJob = `-- name: CreateJob :one

INSERT INTO jobs(type, state,image_path,params)
VALUES ($1,$2,$3,$4)
RETURNING id
`

type CreateJobParams struct {
	Type      JobType
	State     JobState
	ImagePath string
	Params    json.RawMessage
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Type,
		arg.State,
		arg.ImagePath,
		arg.Params,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getJobById = `-- name: GetJobById :one

SELECT id, type, state, image_path, params, created_at, updated_at, retry_counter
FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.State,
		&i.ImagePath,
		&i.Params,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCounter,
	)
	return i, err
}

const getJobIfQueued = `-- name: GetJobIfQueued :one

UPDATE jobs
SET state = 'processing',
updated_at = NOW()
WHERE id = $1 AND state = 'queued'
RETURNING id, type, state, image_path, params, created_at, updated_at, retry_counter
`

func (q *Queries) GetJobIfQueued(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobIfQueued, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.State,
		&i.ImagePath,
		&i.Params,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCounter,
	)
	return i, err
}

const getLeftJobs = `-- name: GetLeftJobs :many

SELECT id
FROM jobs
WHERE state = 'queued' 
ORDER BY created_at
`

func (q *Queries) GetLeftJobs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getLeftJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeJobsFromDBForTest = `-- name: RemoveJobsFromDBForTest :exec

TRUNCATE TABLE jobs RESTART IDENTITY
`

func (q *Queries) RemoveJobsFromDBForTest(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeJobsFromDBForTest)
	return err
}

const updateJobId = `-- name: UpdateJobId :exec

UPDATE jobs
SET state = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateJobIdParams struct {
	State JobState
	ID    int64
}

func (q *Queries) UpdateJobId(ctx context.Context, arg UpdateJobIdParams) error {
	_, err := q.db.ExecContext(ctx, updateJobId, arg.State, arg.ID)
	return err
}

const updateJobStateAtRestart = `-- name: UpdateJobStateAtRestart :exec

UPDATE jobs
SET state = 'queued',
updated_at = NOW()
WHERE state = 'processing'
`

func (q *Queries) UpdateJobStateAtRestart(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateJobStateAtRestart)
	return err
}

const updateRetryCounterAndChangeState = `-- name: UpdateRetryCounterAndChangeState :exec

UPDATE jobs
SET state = 'queued',
updated_at = NOW(), retry_counter = retry_counter +1
WHERE id = $1
`

func (q *Queries) UpdateRetryCounterAndChangeState(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateRetryCounterAndChangeState, id)
	return err
}
