// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one

INSERT INTO jobs(job_type, state,payload)
VALUES ($1,$2,$3)
RETURNING id
`

type CreateJobParams struct {
	JobType string
	State   JobState
	Payload []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, createJob, arg.JobType, arg.State, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failJobWithError = `-- name: FailJobWithError :exec

UPDATE jobs
SET state = 'fail' , updated_at = NOW(), error = $2, completed_at = NOW()
WHERE id = $1
`

type FailJobWithErrorParams struct {
	ID    int64
	Error pgtype.Text
}

func (q *Queries) FailJobWithError(ctx context.Context, arg FailJobWithErrorParams) error {
	_, err := q.db.Exec(ctx, failJobWithError, arg.ID, arg.Error)
	return err
}

const getJobById = `-- name: GetJobById :one

SELECT id, state, created_at, updated_at, retry_counter, job_type, payload, results, error, completed_at
FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCounter,
		&i.JobType,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.CompletedAt,
	)
	return i, err
}

const getJobIfQueued = `-- name: GetJobIfQueued :one

UPDATE jobs
SET state = 'processing',
updated_at = NOW()
WHERE id = $1 AND state = 'queued'
RETURNING id, state, created_at, updated_at, retry_counter, job_type, payload, results, error, completed_at
`

func (q *Queries) GetJobIfQueued(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJobIfQueued, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCounter,
		&i.JobType,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.CompletedAt,
	)
	return i, err
}

const getLeftJobs = `-- name: GetLeftJobs :many

SELECT id
FROM jobs
WHERE state = 'queued' 
ORDER BY created_at
`

func (q *Queries) GetLeftJobs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getLeftJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultFromJob = `-- name: GetResultFromJob :one

SELECT state, results, error,completed_at FROM jobs
WHERE id = $1
`

type GetResultFromJobRow struct {
	State       JobState
	Results     []byte
	Error       pgtype.Text
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) GetResultFromJob(ctx context.Context, id int64) (GetResultFromJobRow, error) {
	row := q.db.QueryRow(ctx, getResultFromJob, id)
	var i GetResultFromJobRow
	err := row.Scan(
		&i.State,
		&i.Results,
		&i.Error,
		&i.CompletedAt,
	)
	return i, err
}

const removeJobsFromDBForTest = `-- name: RemoveJobsFromDBForTest :exec

TRUNCATE TABLE jobs RESTART IDENTITY
`

func (q *Queries) RemoveJobsFromDBForTest(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeJobsFromDBForTest)
	return err
}

const successJobWithResult = `-- name: SuccessJobWithResult :exec

UPDATE jobs
SET state = 'success' , updated_at = NOW(), results = $2, completed_at = NOW()
WHERE id = $1
`

type SuccessJobWithResultParams struct {
	ID      int64
	Results []byte
}

func (q *Queries) SuccessJobWithResult(ctx context.Context, arg SuccessJobWithResultParams) error {
	_, err := q.db.Exec(ctx, successJobWithResult, arg.ID, arg.Results)
	return err
}

const updateJobId = `-- name: UpdateJobId :exec

UPDATE jobs
SET state = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateJobIdParams struct {
	State JobState
	ID    int64
}

func (q *Queries) UpdateJobId(ctx context.Context, arg UpdateJobIdParams) error {
	_, err := q.db.Exec(ctx, updateJobId, arg.State, arg.ID)
	return err
}

const updateJobStateAtRestart = `-- name: UpdateJobStateAtRestart :exec

UPDATE jobs
SET state = 'queued',
updated_at = NOW()
WHERE state = 'processing'
`

func (q *Queries) UpdateJobStateAtRestart(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateJobStateAtRestart)
	return err
}

const updateRetryCounterAndChangeState = `-- name: UpdateRetryCounterAndChangeState :exec

UPDATE jobs
SET state = 'queued',
updated_at = NOW(), retry_counter = retry_counter +1
WHERE id = $1
`

func (q *Queries) UpdateRetryCounterAndChangeState(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateRetryCounterAndChangeState, id)
	return err
}
