// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobState string

const (
	JobStateQueued     JobState = "queued"
	JobStateProcessing JobState = "processing"
	JobStateFail       JobState = "fail"
	JobStateSuccess    JobState = "success"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type QueuePriority string

const (
	QueuePriorityHigh   QueuePriority = "high"
	QueuePriorityNormal QueuePriority = "normal"
	QueuePriorityLow    QueuePriority = "low"
)

func (e *QueuePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QueuePriority(s)
	case string:
		*e = QueuePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for QueuePriority: %T", src)
	}
	return nil
}

type NullQueuePriority struct {
	QueuePriority QueuePriority
	Valid         bool // Valid is true if QueuePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQueuePriority) Scan(value interface{}) error {
	if value == nil {
		ns.QueuePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QueuePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQueuePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QueuePriority), nil
}

type Job struct {
	ID           int64
	State        JobState
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	RetryCounter int16
	JobType      string
	Payload      []byte
	Results      []byte
	Error        pgtype.Text
	CompletedAt  pgtype.Timestamptz
	JobPriority  QueuePriority
}
