// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type JobState string

const (
	JobStateQueued     JobState = "queued"
	JobStateProcessing JobState = "processing"
	JobStateFail       JobState = "fail"
	JobStateRetry      JobState = "retry"
	JobStateSuccess    JobState = "success"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type JobType string

const (
	JobTypeResize    JobType = "resize"
	JobTypeCompress  JobType = "compress"
	JobTypeGrayscale JobType = "grayscale"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType
	Valid   bool // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type Job struct {
	ID        int64
	Type      JobType
	State     JobState
	ImagePath string
	Params    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}
